# Generated by Django 5.1.4 on 2025-01-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='note',
            name='position_y',
        ),
        migrations.AddField(
            model_name='note',
            name='position',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.IntegerField(default=4294967040),
        ),
        migrations.AlterField(
            model_name='note',
            name='rotation',
            field=models.FloatField(default=0.0),
        ),
    ]
