# Generated by Django 5.1.4 on 2025-01-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='position',
            field=models.JSONField(),
        ),
    ]
